name: Say Hello

en: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3

      - name: Say Hello
        run: echo "Hello, World!"
